<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b8e249f1-c0d2-4309-9f50-49a1e9b552c2</UserSecretsId>
    <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="GlobalUsings.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="Kephas.AspNetCore.IdentityServer4" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="NSwag.AspNetCore" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Enrichers.Process" />
    <PackageReference Include="Serilog.Enrichers.Thread" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Application\Application.csproj" />
    <ProjectReference Include="..\src\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="..\.dockerignore" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="..\.dockerignore" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="..\.dockerignore" />
  </ItemGroup>

</Project>
